// apps/storefront/src/components/layout/AnnouncementBar.tsx
"use client";

import { cn } from "@/lib/utils";

const announcements = [
  "Free Shipping on Orders Over $100",
  "New Arrivals Every Week",
  "Easy 30-Day Returns",
  "Exclusive Member Rewards",
];

export function AnnouncementBar() {
  return (
    <div className="bg-gradient-to-r from-gold-dark via-gold to-gold-dark py-2.5 overflow-hidden">
      <div className="flex animate-marquee whitespace-nowrap">
        {/* Duplicate announcements for seamless loop */}
        {[...announcements, ...announcements].map((text, index) => (
          <div
            key={index}
            className={cn(
              "flex items-center px-12",
              "text-white text-xs font-medium tracking-widest uppercase"
            )}
          >
            <span>{text}</span>
            <span className="ml-12 opacity-70">✦</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// resources/js/storefront/components/AnnouncementBar.vue
<script>
export default {
    name: 'AnnouncementBar',
    data() {
        return {
            messages: [
                'NEW ARRIVALS EVERY WEEK',
                'EASY 30-DAY RETURNS',
                'EXCLUSIVE MEMBER REWARDS',
                'FREE SHIPPING ON ORDERS OVER $100',
            ],
        };
    },
};
</script>

<template>
    <div class="bg-gold text-white text-[10px] sm:text-xs tracking-[0.32em] uppercase overflow-hidden">
        <div class="flex animate-marquee whitespace-nowrap py-2">
            <span v-for="(m, i) in [...messages, ...messages]" :key="i" class="px-8 flex items-center gap-3">
                <span>{{ m }}</span>
                <span class="text-gold-dark">◆</span>
            </span>
        </div>
    </div>
</template>

<style scoped>
@keyframes marquee {
    from { transform: translateX(0); }
    to   { transform: translateX(-50%); }
}
.animate-marquee {
    animation: marquee 35s linear infinite;
}
</style>
