// apps/storefront/src/components/layout/SearchOverlay.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { X, Search } from "lucide-react";
import { useUIStore } from "@/stores/ui";

export function SearchOverlay() {
  const router = useRouter();
  const { isSearchOpen, closeSearch } = useUIStore();
  const [value, setValue] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (!isSearchOpen) return;
    // Focus the input when the overlay opens.
    const id = window.setTimeout(() => inputRef.current?.focus(), 50);

    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") closeSearch();
    };
    window.addEventListener("keydown", onKey);
    return () => {
      window.clearTimeout(id);
      window.removeEventListener("keydown", onKey);
    };
  }, [isSearchOpen, closeSearch]);

  if (!isSearchOpen) return null;

  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    const q = value.trim();
    if (!q) return;
    closeSearch();
    setValue("");
    router.push(`/shop?q=${encodeURIComponent(q)}`);
  };

  return (
    <div
      className="fixed inset-0 z-[100] bg-black/40 backdrop-blur-sm flex items-start justify-center pt-24 px-4"
      onClick={closeSearch}
      role="dialog"
      aria-modal="true"
      aria-label="Search"
    >
      <div
        className="w-full max-w-2xl bg-white shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <form onSubmit={submit} className="flex items-center gap-3 px-5 py-4 border-b border-black/10">
          <Search className="w-5 h-5 text-black/40" strokeWidth={1.5} />
          <input
            ref={inputRef}
            type="search"
            value={value}
            onChange={(e) => setValue(e.target.value)}
            placeholder="Search products, tags, materials…"
            className="flex-1 bg-transparent text-lg font-display placeholder:text-black/30 focus:outline-none"
          />
          <button
            type="button"
            onClick={closeSearch}
            className="text-black/40 hover:text-black transition-colors"
            aria-label="Close search"
          >
            <X className="w-5 h-5" strokeWidth={1.5} />
          </button>
        </form>
        <div className="px-5 py-4 text-xs text-black/50">
          Press <kbd className="px-1.5 py-0.5 bg-cream border border-black/10 rounded">Enter</kbd> to search ·
          <kbd className="ml-2 px-1.5 py-0.5 bg-cream border border-black/10 rounded">Esc</kbd> to close
        </div>
      </div>
    </div>
  );
}

// resources/js/storefront/components/SearchOverlay.vue
<script>
import { Search, X } from 'lucide-vue-next';

export default {
    name: 'SearchOverlay',
    components: { Search, X },
    props: {
        open: { type: Boolean, default: false },
    },
    emits: ['close'],
    data() {
        return {
            term: '',
            results: [],
            loading: false,
            // Cheap debounce — abort the in-flight fetch if the user keeps typing.
            inflight: null,
        };
    },
    watch: {
        open(v) {
            if (v) {
                this.$nextTick(() => this.$refs.input?.focus());
                document.body.style.overflow = 'hidden';
                window.addEventListener('keydown', this.onKey);
            } else {
                this.term = '';
                this.results = [];
                document.body.style.overflow = '';
                window.removeEventListener('keydown', this.onKey);
            }
        },
        term(v) { this.runSearch(v); },
    },
    beforeUnmount() {
        document.body.style.overflow = '';
        window.removeEventListener('keydown', this.onKey);
    },
    methods: {
        close() { this.$emit('close'); },
        onKey(e) { if (e.key === 'Escape') this.close(); },
        async runSearch(q) {
            const v = q.trim();
            if (this.inflight) this.inflight.abort();
            if (!v) { this.results = []; this.loading = false; return; }
            this.loading = true;
            this.inflight = new AbortController();
            try {
                const r = await fetch(`/api/store/products?limit=8&q=${encodeURIComponent(v)}`,
                    { signal: this.inflight.signal });
                if (!r.ok) return;
                const data = await r.json();
                this.results = data.products || [];
            } catch (e) {
                if (e.name !== 'AbortError') this.results = [];
            } finally { this.loading = false; }
        },
        submit() {
            if (this.term.trim()) {
                this.$router.push({ path: '/shop', query: { q: this.term.trim() } });
                this.close();
            }
        },
    },
};
</script>

<template>
    <transition name="search-fade">
        <div v-if="open" class="fixed inset-0 z-50 bg-cream/95 backdrop-blur overflow-y-auto overscroll-contain pb-10" @click.self="close">
            <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 pt-16">
                <div class="flex items-center justify-between mb-6">
                    <p class="font-script text-2xl text-gold">Find</p>
                    <button @click="close" class="w-11 h-11 -mr-2 inline-flex items-center justify-center hover:text-gold transition-colors" aria-label="Close search">
                        <X class="w-5 h-5" />
                    </button>
                </div>
                <form @submit.prevent="submit" class="flex items-center gap-3 border-b-2 border-gold/40 focus-within:border-gold pb-2">
                    <Search class="w-5 h-5 text-gold-dark" />
                    <input
                        ref="input"
                        v-model="term"
                        type="search"
                        placeholder="Search dresses, bags, brands…"
                        class="flex-1 bg-transparent text-lg md:text-2xl font-display py-2 focus:outline-none placeholder:text-black/40"
                    />
                    <button v-if="term" type="button" @click="term = ''" class="text-xs tracking-widest uppercase text-black/55 hover:text-gold">Clear</button>
                </form>

                <div v-if="loading" class="mt-8 text-[10px] tracking-widest uppercase text-black/55 animate-pulse">Searching…</div>

                <div v-else-if="!term" class="mt-8 text-sm text-black/55">
                    Try “floral”, “evening gown”, or a category like “bags”.
                </div>

                <div v-else-if="!results.length" class="mt-8 text-sm text-black/55">
                    No matches for <strong>"{{ term }}"</strong>. Try a shorter or different term.
                </div>

                <ul v-else class="mt-6 divide-y divide-gold/10">
                    <li v-for="p in results" :key="p.id">
                        <router-link :to="`/shop/${p.handle}`" @click="close" class="flex gap-4 py-3 hover:bg-cream-dark/30 px-2 transition-colors">
                            <div class="w-14 h-16 bg-cream-dark flex-shrink-0 overflow-hidden">
                                <img v-if="p.thumbnail" :src="p.thumbnail" :alt="p.title" class="w-full h-full object-cover object-top" />
                            </div>
                            <div class="flex-1 min-w-0">
                                <p class="font-display text-base line-clamp-1">{{ p.title }}</p>
                                <p v-if="p.subtitle" class="text-xs text-black/55 line-clamp-1">{{ p.subtitle }}</p>
                            </div>
                            <p class="text-sm font-medium">{{ p.price_label || '—' }}</p>
                        </router-link>
                    </li>
                </ul>

                <div v-if="results.length" class="mt-6 text-center">
                    <button @click="submit" class="text-xs tracking-widest uppercase text-gold-dark hover:text-gold underline">
                        See all results →
                    </button>
                </div>
            </div>
        </div>
    </transition>
</template>

<style scoped>
.search-fade-enter-active, .search-fade-leave-active { transition: opacity 0.18s; }
.search-fade-enter-from, .search-fade-leave-to { opacity: 0; }
</style>
