// Lavavel_Version/resources/js/storefront/pages/Shop.vue
<script>
export default {
    name: 'ShopPage',
    data() {
        return {
            filters: { category: '', size: '', priceMax: null },
            sort: 'featured',
        };
    },
    computed: {
        activeCategory() {
            return this.$route.query.category || 'All';
        },
    },
};
</script>

<template>
    <div class="max-w-[1600px] mx-auto px-[5%] py-12">
        <div class="text-center mb-10">
            <p class="font-script text-3xl text-gold mb-2">Curated</p>
            <h1 class="font-display text-4xl md:text-5xl tracking-widest uppercase capitalize">
                {{ activeCategory }}
            </h1>
        </div>

        <div class="grid grid-cols-12 gap-8">
            <!-- Filter rail -->
            <aside class="hidden lg:block lg:col-span-3 border-r border-gold/10 pr-6">
                <h3 class="font-display text-sm tracking-widest uppercase text-gold mb-4">Filters</h3>
                <div class="space-y-6 text-sm">
                    <div>
                        <p class="font-medium mb-2">Category</p>
                        <ul class="space-y-1 text-black/70">
                            <li v-for="c in ['Women', 'Men', 'Children', 'Sale']" :key="c">
                                <button class="hover:text-gold transition-colors">{{ c }}</button>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <p class="font-medium mb-2">Size</p>
                        <div class="flex flex-wrap gap-2">
                            <button v-for="s in ['XS','S','M','L','XL']" :key="s" class="border border-black/15 px-3 py-1 text-xs hover:border-gold transition-colors">{{ s }}</button>
                        </div>
                    </div>
                </div>
            </aside>

            <!-- Product grid placeholder -->
            <div class="col-span-12 lg:col-span-9">
                <div class="grid grid-cols-2 sm:grid-cols-3 gap-3">
                    <router-link
                        v-for="n in 12"
                        :key="n"
                        :to="`/shop/sample-product-${n}`"
                        class="block group"
                    >
                        <div class="aspect-[3/4] bg-gradient-to-br from-cream-dark to-blush mb-2 group-hover:opacity-90 transition-opacity" />
                        <p class="font-display text-sm leading-tight">Sample Product {{ n }}</p>
                        <p class="text-xs text-black/70">$249.00</p>
                    </router-link>
                </div>
                <p class="text-center text-xs text-black/50 mt-12 tracking-widest uppercase">
                    Catalogue + filters wire up in Milestone 3
                </p>
            </div>
        </div>
    </div>
</template>

// apps/storefront/src/app/shop/page.tsx
import { Suspense } from "react";
import { Metadata } from "next";
import Link from "next/link";
import { ChevronRight } from "lucide-react";
import { ShopContent } from "@/components/shop";

export const metadata: Metadata = {
  title: "Shop All | BLESSLUXE",
  description:
    "Browse our curated collection of luxury fashion for women, men, and children.",
};

// Mock categories for breadcrumb titles
const categoryTitles: Record<string, string> = {
  women: "Women's Collection",
  men: "Men's Collection",
  children: "Children's Collection",
  dresses: "Dresses",
  tops: "Tops & Blouses",
  bottoms: "Pants & Skirts",
  outerwear: "Outerwear",
  accessories: "Accessories",
  sale: "Sale Items",
};

interface ShopPageProps {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}

export default async function ShopPage({ searchParams }: ShopPageProps) {
  const params = await searchParams;
  const category =
    typeof params.category === "string" ? params.category : null;
  const title = category
    ? categoryTitles[category] || "Shop"
    : "Shop All Collections";

  return (
    <main className="min-h-screen bg-cream">
      {/* Page Header */}
      <div className="bg-gradient-to-b from-cream-dark to-cream">
        <div className="max-w-[1400px] mx-auto px-[5%] py-8">
          {/* Breadcrumb */}
          <nav
            className="flex items-center gap-2 text-sm text-black/60 mb-4"
            aria-label="Breadcrumb"
          >
            <Link href="/" className="hover:text-gold transition-colors">
              Home
            </Link>
            <ChevronRight className="w-4 h-4" />
            <span className="text-gold font-medium">Shop</span>
            {category && (
              <>
                <ChevronRight className="w-4 h-4" />
                <span className="text-gold font-medium">
                  {categoryTitles[category] || category}
                </span>
              </>
            )}
          </nav>

          {/* Title */}
          <h1 className="font-display text-4xl md:text-5xl text-black">
            {title}
          </h1>
        </div>
      </div>

      {/* Shop Content */}
      <Suspense
        fallback={
          <div className="max-w-[1400px] mx-auto px-[5%] py-8">
            <div className="animate-pulse">
              <div className="h-8 bg-cream-dark rounded w-48 mb-8" />
              <div className="grid grid-cols-2 md:grid-cols-3 gap-6">
                {[...Array(6)].map((_, i) => (
                  <div key={i} className="space-y-4">
                    <div className="aspect-[3/4] bg-cream-dark rounded-lg" />
                    <div className="h-4 bg-cream-dark rounded w-3/4" />
                    <div className="h-4 bg-cream-dark rounded w-1/2" />
                  </div>
                ))}
              </div>
            </div>
          </div>
        }
      >
        <ShopContent />
      </Suspense>
    </main>
  );
}
