// apps/admin/src/app/affiliates/page.tsx
"use client";

import { useEffect, useState, FormEvent } from "react";
import { Plus, DollarSign } from "lucide-react";
import { api } from "@/lib/api";
import { useAuthGate } from "@/lib/useAuthGate";
import type { Affiliate } from "@/lib/types";
import { AdminShell } from "@/components/AdminShell";
import { useDialog } from "@/components/Dialog";
import { Pagination, paginate } from "@/components/Pagination";
import {
  Modal,
  Field,
  PageHeader,
  inputCls,
  btnPrimary,
  btnGhost,
  btnDanger,
} from "@/components/Modal";

const STATUSES = ["pending", "active", "inactive"] as const;

const STATUS_BADGE: Record<Affiliate["status"], string> = {
  active: "badge badge-success",
  inactive: "badge badge-mute",
  pending: "badge badge-warn",
};

export default function AffiliatesPage() {
  const { user, loading } = useAuthGate();
  const dialog = useDialog();
  const [affiliates, setAffiliates] = useState<Affiliate[]>([]);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(25);
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Affiliate | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = async () => {
    const res = await api.get<{ affiliates: Affiliate[] }>("/admin/affiliates");
    setAffiliates(res.affiliates);
  };

  useEffect(() => {
    if (user) void load();
  }, [user]);

  const onDelete = async (a: Affiliate) => {
    const ok = await dialog.confirm({
      title: `Delete affiliate ${a.email}?`,
      message: "Sales attributed to this affiliate stay on record, but their code will stop working.",
      tone: "danger",
      confirmLabel: "Delete affiliate",
    });
    if (!ok) return;
    await api.delete(`/admin/affiliates/${a.id}`);
    await load();
  };

  const onPayout = async (a: Affiliate) => {
    const amountStr = await dialog.prompt({
      title: `Create payout for ${a.email}`,
      message: (
        <>
          Outstanding earnings:{" "}
          <span className="font-display text-base">
            ${((a.total_earnings - a.paid_out) / 100).toFixed(2)}
          </span>
        </>
      ),
      inputLabel: "Amount (in cents)",
      inputType: "number",
      placeholder: "e.g. 12500 = $125.00",
      required: true,
      tone: "info",
      confirmLabel: "Create payout",
      validate: (val) => {
        const n = Number(val);
        if (!Number.isFinite(n) || n <= 0) return "Enter a positive amount in cents.";
        return null;
      },
    });
    if (amountStr == null) return;
    const amount = Number(amountStr);
    if (!amount || amount <= 0) return;
    await api.post(`/admin/affiliates/${a.id}/payouts`, { amount });
    await load();
  };

  const onSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setBusy(true);
    setError(null);
    const fd = new FormData(e.currentTarget);
    const body = {
      email: String(fd.get("email") || "").trim(),
      first_name: String(fd.get("first_name") || "") || undefined,
      last_name: String(fd.get("last_name") || "") || undefined,
      code: String(fd.get("code") || "") || undefined,
      commission_rate: Number(fd.get("commission_rate") || 10),
      status: String(fd.get("status") || "pending"),
    };
    try {
      if (editing) {
        await api.patch(`/admin/affiliates/${editing.id}`, body);
      } else {
        await api.post("/admin/affiliates", body);
      }
      setOpen(false);
      await load();
    } catch (err: unknown) {
      setError((err as { message?: string }).message || "Failed");
    } finally {
      setBusy(false);
    }
  };

  if (loading || !user) {
    return (
      <div className="flex h-screen items-center justify-center">
        <p className="font-script text-2xl text-[var(--gold-dark)]">Bless</p>
      </div>
    );
  }

  return (
    <AdminShell user={user}>
      <PageHeader
        title="Affiliates"
        subtitle="Promo codes, commission rates, sales attribution, and payouts."
        actions={
          <button onClick={() => { setEditing(null); setError(null); setOpen(true); }} className={btnPrimary}>
            <Plus className="mr-1.5 h-3.5 w-3.5" />
            New affiliate
          </button>
        }
      />

      <div
        className="overflow-hidden bg-white"
        style={{ border: "1px solid var(--line)", borderRadius: 4 }}
      >
        <table className="w-full text-sm">
          <thead style={{ background: "var(--cream)" }}>
            <tr className="text-left text-[10px] font-semibold uppercase tracking-luxe text-[var(--ink-muted)]">
              <th className="px-5 py-3">Code</th>
              <th className="px-5 py-3">Affiliate</th>
              <th className="px-5 py-3">Email</th>
              <th className="px-5 py-3">Rate</th>
              <th className="px-5 py-3">Status</th>
              <th className="px-5 py-3">Earnings</th>
              <th className="px-5 py-3 text-right pr-5">Actions</th>
            </tr>
          </thead>
          <tbody>
            {paginate(affiliates, page, pageSize).map((a) => (
              <tr
                key={a.id}
                className="transition-colors hover:bg-[var(--cream)]"
                style={{ borderTop: "1px solid var(--line-soft)" }}
              >
                <td className="px-5 py-4 font-mono text-xs font-semibold text-[var(--gold-dark)]">{a.code}</td>
                <td className="px-5 py-4 font-display text-base font-medium tracking-soft">
                  {[a.first_name, a.last_name].filter(Boolean).join(" ") || "—"}
                </td>
                <td className="px-5 py-4 text-[var(--ink-light)]">{a.email}</td>
                <td className="px-5 py-4 font-display text-base">{a.commission_rate}%</td>
                <td className="px-5 py-4">
                  <span className={STATUS_BADGE[a.status]}>{a.status}</span>
                </td>
                <td className="px-5 py-4">
                  <span className="font-display text-base">${(a.total_earnings / 100).toFixed(2)}</span>
                  <span className="ml-1 text-[10px] uppercase tracking-luxe text-[var(--ink-muted)]">
                    paid ${(a.paid_out / 100).toFixed(2)}
                  </span>
                </td>
                <td className="px-5 py-4 text-right">
                  <div className="flex items-center justify-end gap-2">
                    <button onClick={() => onPayout(a)} className={`${btnGhost} btn-sm`}>
                      <DollarSign className="mr-1 h-3 w-3" /> Payout
                    </button>
                    <button onClick={() => { setEditing(a); setError(null); setOpen(true); }} className={`${btnGhost} btn-sm`}>Edit</button>
                    <button onClick={() => onDelete(a)} className={btnDanger}>Delete</button>
                  </div>
                </td>
              </tr>
            ))}
            {affiliates.length === 0 && (
              <tr>
                <td colSpan={7} className="px-5 py-16 text-center">
                  <p className="font-display text-2xl text-[var(--ink-muted)]">No affiliates yet</p>
                </td>
              </tr>
            )}
          </tbody>
        </table>
        {affiliates.length > 0 && (
          <Pagination
            page={page}
            pageSize={pageSize}
            total={affiliates.length}
            onPageChange={setPage}
            onPageSizeChange={(s) => { setPageSize(s); setPage(1); }}
            itemNoun="affiliates"
          />
        )}
      </div>

      <Modal
        open={open}
        onClose={() => setOpen(false)}
        title={editing ? `Edit · ${editing.email}` : "New affiliate"}
        footer={
          <>
            <button onClick={() => setOpen(false)} className={btnGhost} type="button">Cancel</button>
            <button form="aff-form" type="submit" disabled={busy} className={btnPrimary}>
              {busy ? "Saving…" : editing ? "Save" : "Create"}
            </button>
          </>
        }
      >
        <form id="aff-form" onSubmit={onSubmit} className="space-y-5">
          <div className="grid grid-cols-2 gap-4">
            <Field label="First name">
              <input name="first_name" defaultValue={editing?.first_name || ""} className={inputCls} />
            </Field>
            <Field label="Last name">
              <input name="last_name" defaultValue={editing?.last_name || ""} className={inputCls} />
            </Field>
          </div>
          <Field label="Email" required>
            <input type="email" name="email" required defaultValue={editing?.email || ""} className={inputCls} />
          </Field>
          <Field label="Promo code" hint="Auto-generated if blank">
            <input name="code" defaultValue={editing?.code || ""} className={inputCls} />
          </Field>
          <div className="grid grid-cols-2 gap-4">
            <Field label="Commission %">
              <input type="number" step="0.1" name="commission_rate" defaultValue={editing?.commission_rate ?? 10} className={inputCls} />
            </Field>
            <Field label="Status">
              <select name="status" defaultValue={editing?.status || "pending"} className="select">
                {STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}
              </select>
            </Field>
          </div>
          {error && (
            <div className="rounded-sm border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{error}</div>
          )}
        </form>
      </Modal>
    </AdminShell>
  );
}

// resources/js/admin/pages/Affiliates.vue
<script>
import { api } from '../../lib/api.js';
import { confirmDialog, toast } from '../../lib/dialog.js';
import IconButton from '../components/IconButton.vue';
import { Pencil, Trash2, Check, LoaderCircle } from 'lucide-vue-next';

export default {
    name: 'AdminAffiliates',
    components: { IconButton, Pencil, Trash2, Check, LoaderCircle },
    data() {
        return {
            affiliates: [], pagination: null, loading: true,
            q: '', page: 1,
            showForm: false, editingId: null,
            form: this.emptyForm(),
            saving: false, error: '',
            approvingId: null,
            notice: '',
        };
    },
    mounted() { this.fetchAll(); },
    methods: {
        emptyForm() {
            return { code: '', email: '', first_name: '', last_name: '', commission_rate: 10, status: 'pending' };
        },
        /**
         * Approve: flips to active, which is what assigns the share code and
         * sends the welcome email and in-app notification. One action rather
         * than editing a status dropdown and hoping the side effects fire.
         */
        async approve(a) {
            const name = [a.first_name, a.last_name].filter(Boolean).join(' ') || a.email;
            if (!await confirmDialog({
                title: `Approve ${name}?`,
                body: "They'll be assigned a share code and emailed straight away.",
                confirmLabel: 'Approve',
            })) return;

            this.approvingId = a.id;
            this.error = ''; this.notice = '';
            try {
                const d = await api.put(`/api/admin/affiliates/${a.id}`, { status: 'active' });
                await this.fetchAll();
                const code = d.affiliate?.code;
                this.notice = code
                    ? `${name} approved — their code is ${code}.`
                    : `${name} approved.`;
            } catch (e) {
                this.error = e.payload?.error || 'Could not approve that affiliate.';
            } finally { this.approvingId = null; }
        },
        async fetchAll() {
            this.loading = true;
            try {
                const params = new URLSearchParams({ page: this.page, limit: 25 });
                if (this.q) params.set('q', this.q);
                const data = await api.get(`/api/admin/affiliates?${params}`);
                this.affiliates = data.affiliates || [];
                this.pagination = data.pagination;
            } finally { this.loading = false; }
        },
        startNew() {
            this.editingId = null; this.form = this.emptyForm();
            this.showForm = true; this.error = '';
        },
        startEdit(a) {
            this.editingId = a.id;
            this.form = { code: a.code, email: a.email, first_name: a.first_name || '', last_name: a.last_name || '', commission_rate: a.commission_rate, status: a.status };
            this.showForm = true; this.error = '';
        },
        cancel() { this.showForm = false; this.editingId = null; this.error = ''; },
        async save() {
            this.saving = true; this.error = '';
            try {
                if (this.editingId) {
                    const body = { commission_rate: this.form.commission_rate, status: this.form.status, first_name: this.form.first_name, last_name: this.form.last_name };
                    await api.put(`/api/admin/affiliates/${this.editingId}`, body);
                } else {
                    await api.post('/api/admin/affiliates', this.form);
                }
                this.cancel();
                await this.fetchAll();
            } catch (e) {
                this.error = e.payload?.error
                    || (e.payload?.errors && Object.values(e.payload.errors)[0]?.[0])
                    || 'Could not save.';
            } finally { this.saving = false; }
        },
        async remove(a) {
            // A pending applicant has no code, so name them instead of showing
            // "Delete affiliate undefined?".
            const who = a.code || [a.first_name, a.last_name].filter(Boolean).join(' ') || a.email;
            if (!await confirmDialog({
                title: `Delete affiliate ${who}?`,
                body: 'Their sales history stays in place. This cannot be undone.',
                confirmLabel: 'Delete',
                tone: 'danger',
            })) return;
            try {
                await api.del(`/api/admin/affiliates/${a.id}`);
                await this.fetchAll();
            } catch (e) { toast(e.payload?.error || 'Could not delete.', { tone: 'error' }); }
        },
    },
};
</script>

<template>
    <div>
        <header class="flex items-center justify-between mb-8">
            <div>
                <p class="text-xs tracking-widest uppercase text-zinc-500">Partners</p>
                <h1 class="text-2xl font-semibold">Affiliates</h1>
            </div>
            <button @click="startNew" class="bg-gold text-white px-5 py-2 text-xs font-semibold tracking-[0.3em] uppercase hover:bg-gold-dark">New Affiliate</button>
        </header>

        <!-- Approval mints a code and emails the affiliate, so confirm what happened. -->
        <p v-if="notice" class="bg-emerald-50 border border-emerald-200 text-sm text-emerald-800 p-3 mb-4">{{ notice }}</p>
        <p v-if="error && !showForm" class="bg-red-50 border border-red-200 text-sm text-red-700 p-3 mb-4">{{ error }}</p>

        <div class="mb-4 flex gap-2">
            <input v-model="q" @keyup.enter="page = 1; fetchAll()" placeholder="Search code or email…" class="border border-zinc-300 px-3 py-2 text-sm w-72" />
            <button @click="page = 1; fetchAll()" class="border border-zinc-300 px-4 py-2 text-xs tracking-widest uppercase hover:bg-zinc-100">Search</button>
        </div>

        <div v-if="showForm" class="bg-white border border-gold/30 p-5 mb-6">
            <h2 class="font-semibold mb-3">{{ editingId ? 'Edit affiliate' : 'New affiliate' }}</h2>
            <div class="grid grid-cols-2 gap-3">
                <input v-model="form.code" :disabled="!!editingId" placeholder="Code (e.g. JANE10)" class="border border-zinc-300 px-3 py-2 font-mono uppercase disabled:bg-zinc-100" />
                <input v-model="form.email" :disabled="!!editingId" type="email" placeholder="Email" class="border border-zinc-300 px-3 py-2 disabled:bg-zinc-100" />
                <input v-model="form.first_name" placeholder="First name" class="border border-zinc-300 px-3 py-2" />
                <input v-model="form.last_name"  placeholder="Last name"  class="border border-zinc-300 px-3 py-2" />
                <div>
                    <label class="block text-xs tracking-widest uppercase text-zinc-500 mb-1">Commission (%)</label>
                    <input v-model.number="form.commission_rate" type="number" step="0.5" min="0" max="100" class="w-full border border-zinc-300 px-3 py-2" />
                </div>
                <div>
                    <label class="block text-xs tracking-widest uppercase text-zinc-500 mb-1">Status</label>
                    <select v-model="form.status" class="w-full border border-zinc-300 px-3 py-2">
                        <option value="pending">Pending</option>
                        <option value="active">Active</option>
                        <option value="paused">Paused</option>
                    </select>
                </div>
            </div>
            <p v-if="error" class="text-sm text-red-600 mt-3">{{ error }}</p>
            <div class="flex justify-end gap-2 mt-4">
                <button @click="cancel" class="px-4 py-2 text-xs tracking-widest uppercase text-zinc-600">Cancel</button>
                <button @click="save" :disabled="saving" class="bg-gold text-white px-4 py-2 text-xs font-semibold tracking-widest uppercase hover:bg-gold-dark disabled:opacity-50">
                    {{ saving ? 'Saving…' : 'Save' }}
                </button>
            </div>
        </div>

        <div class="bg-white border border-zinc-200">
            <table class="w-full text-sm">
                <thead class="bg-zinc-50 text-xs tracking-widest uppercase text-zinc-500">
                    <tr>
                        <th class="px-5 py-3 text-left">Code</th>
                        <th class="px-5 py-3 text-left">Owner</th>
                        <th class="px-5 py-3 text-left">Commission</th>
                        <th class="px-5 py-3 text-left">Earnings</th>
                        <th class="px-5 py-3 text-left">Status</th>
                        <th class="px-5 py-3"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-if="loading"><td colspan="6" class="px-5 py-8 text-center text-zinc-400">Loading…</td></tr>
                    <tr v-else-if="!affiliates.length"><td colspan="6" class="px-5 py-8 text-center text-zinc-400">No affiliates yet.</td></tr>
                    <tr v-for="a in affiliates" :key="a.id" class="border-t border-zinc-100">
                        <td class="px-5 py-3 font-mono">
                            <router-link :to="`/admin/affiliates/${a.id}`" class="hover:text-gold">
                                <!-- Pending applicants have no code yet; a blank
                                     cell reads as missing data rather than "not
                                     assigned until you approve". -->
                                <span v-if="a.code">{{ a.code }}</span>
                                <span v-else class="text-zinc-400 font-sans text-xs tracking-widest uppercase">Not assigned</span>
                            </router-link>
                        </td>
                        <td class="px-5 py-3">{{ [a.first_name, a.last_name].filter(Boolean).join(' ') || a.email }}</td>
                        <td class="px-5 py-3">{{ a.commission_rate }}%</td>
                        <td class="px-5 py-3">{{ a.total_earnings }} <span class="text-zinc-400 text-[10px]">({{ a.paid_out }} paid)</span></td>
                        <td class="px-5 py-3">
                            <span :class="['text-xs px-2 py-0.5 rounded', {
                                'bg-amber-100 text-amber-700': a.status === 'pending',
                                'bg-emerald-100 text-emerald-700': a.status === 'active',
                                'bg-zinc-100 text-zinc-600': a.status === 'paused',
                            }]">{{ a.status }}</span>
                        </td>
                        <td class="px-5 py-3 text-right">
                            <div class="inline-flex items-center gap-1">
                                <!-- Only meaningful while pending; approving is what
                                     mints the code and notifies them. -->
                                <IconButton
                                    v-if="a.status === 'pending'"
                                    tone="positive"
                                    label="Approve — assigns their code and emails them"
                                    :disabled="approvingId === a.id"
                                    @click="approve(a)"
                                >
                                    <LoaderCircle v-if="approvingId === a.id" class="w-4 h-4 animate-spin" />
                                    <Check v-else class="w-4 h-4" />
                                </IconButton>
                                <IconButton label="Edit affiliate" @click="startEdit(a)">
                                    <Pencil class="w-4 h-4" />
                                </IconButton>
                                <IconButton label="Delete affiliate" tone="danger" @click="remove(a)">
                                    <Trash2 class="w-4 h-4" />
                                </IconButton>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>
