// resources/js/admin/pages/Reviews.vue
<script>
import { api } from '../../lib/api.js';
import { toast } from '../../lib/dialog.js';
import IconButton from '../components/IconButton.vue';
import { Check, X, MessageSquareReply } from 'lucide-vue-next';

export default {
    name: 'AdminReviews',
    components: { IconButton, Check, X, MessageSquareReply },
    data() {
        return {
            reviews: [], pagination: null, loading: true,
            statusFilter: '', q: '', page: 1,
            replying: null, response: '',
            saving: false, error: '',
        };
    },
    mounted() { this.fetchAll(); },
    methods: {
        async fetchAll() {
            this.loading = true;
            try {
                const params = new URLSearchParams({ page: this.page, limit: 25 });
                if (this.q) params.set('q', this.q);
                if (this.statusFilter) params.set('status', this.statusFilter);
                const data = await api.get(`/api/admin/reviews?${params}`);
                this.reviews = data.reviews || [];
                this.pagination = data.pagination;
            } finally { this.loading = false; }
        },
        async setStatus(r, status) {
            try {
                await api.put(`/api/admin/reviews/${r.id}`, { status });
                r.status = status;
            } catch (e) { toast(e.payload?.error || 'Could not update.', { tone: 'error' }); }
        },
        startReply(r) {
            this.replying = r; this.response = r.admin_response || ''; this.error = '';
        },
        cancelReply() { this.replying = null; },
        async saveReply() {
            this.saving = true; this.error = '';
            try {
                await api.put(`/api/admin/reviews/${this.replying.id}`, { admin_response: this.response });
                this.replying.admin_response = this.response;
                this.cancelReply();
            } catch (e) {
                this.error = e.payload?.error || 'Could not save reply.';
            } finally { this.saving = false; }
        },
    },
};
</script>

<template>
    <div>
        <header class="flex flex-wrap items-center justify-between gap-3 mb-8">
            <div>
                <p class="text-xs tracking-widest uppercase text-zinc-500">Moderation</p>
                <h1 class="text-2xl font-semibold">Reviews</h1>
            </div>
        </header>

        <div class="mb-4 flex flex-wrap gap-2 items-center">
            <input v-model="q" @keyup.enter="page = 1; fetchAll()" placeholder="Search title, content or email…" class="border border-zinc-300 px-3 py-2 text-sm w-full sm:w-72" />
            <select v-model="statusFilter" @change="page = 1; fetchAll()" class="border border-zinc-300 px-3 py-2 text-sm">
                <option value="">All statuses</option>
                <option value="pending">Pending</option>
                <option value="approved">Approved</option>
                <option value="rejected">Rejected</option>
            </select>
            <button @click="page = 1; fetchAll()" class="border border-zinc-300 px-4 py-2 text-xs tracking-widest uppercase hover:bg-zinc-100">Search</button>
        </div>

        <div v-if="replying" class="bg-white border border-gold/30 p-5 mb-6">
            <h2 class="font-semibold mb-1">Reply to {{ replying.customer_name || replying.customer_email }}</h2>
            <p class="text-xs text-zinc-500 mb-3 italic">"{{ replying.content }}"</p>
            <textarea v-model="response" rows="3" class="w-full border border-zinc-300 px-3 py-2" placeholder="Your response…"></textarea>
            <p v-if="error" class="text-sm text-red-600 mt-3">{{ error }}</p>
            <div class="flex justify-end gap-2 mt-4">
                <button @click="cancelReply" class="px-4 py-2 text-xs tracking-widest uppercase text-zinc-600">Cancel</button>
                <button @click="saveReply" :disabled="saving" class="bg-gold text-white px-4 py-2 text-xs font-semibold tracking-widest uppercase hover:bg-gold-dark disabled:opacity-50">
                    {{ saving ? 'Saving…' : 'Save Reply' }}
                </button>
            </div>
        </div>

        <div class="bg-white border border-zinc-200">
            <table class="w-full text-sm">
                <thead class="bg-zinc-50 text-xs tracking-widest uppercase text-zinc-500">
                    <tr>
                        <th class="px-5 py-3 text-left">Product</th>
                        <th class="px-5 py-3 text-left">Rating</th>
                        <th class="px-5 py-3 text-left">Customer</th>
                        <th class="px-5 py-3 text-left">Review</th>
                        <th class="px-5 py-3 text-left">Status</th>
                        <th class="px-5 py-3"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-if="loading"><td colspan="6" class="px-5 py-8 text-center text-zinc-400">Loading…</td></tr>
                    <tr v-else-if="!reviews.length"><td colspan="6" class="px-5 py-8 text-center text-zinc-400">No reviews match.</td></tr>
                    <tr v-for="r in reviews" :key="r.id" class="border-t border-zinc-100">
                        <td class="px-5 py-3 text-xs">{{ r.product_title }}</td>
                        <td class="px-5 py-3">{{ '★'.repeat(r.rating) }}<span class="text-zinc-300">{{ '★'.repeat(5 - r.rating) }}</span></td>
                        <td class="px-5 py-3 text-xs">{{ r.customer_name || r.customer_email || '—' }}</td>
                        <td class="px-5 py-3">
                            <p class="font-medium text-xs">{{ r.title }}</p>
                            <p class="text-xs text-zinc-600 line-clamp-2">{{ r.content }}</p>
                            <p v-if="r.admin_response" class="text-xs text-gold-dark mt-1 italic">↪ {{ r.admin_response }}</p>
                        </td>
                        <td class="px-5 py-3">
                            <span :class="['text-xs px-2 py-0.5 rounded', {
                                'bg-amber-100 text-amber-700': r.status === 'pending',
                                'bg-emerald-100 text-emerald-700': r.status === 'approved',
                                'bg-red-100 text-red-700': r.status === 'rejected',
                            }]">{{ r.status }}</span>
                        </td>
                        <td class="px-5 py-3 text-right">
                            <div class="inline-flex items-center gap-1">
                                <IconButton v-if="r.status !== 'approved'" label="Approve review" tone="positive" @click="setStatus(r, 'approved')">
                                    <Check class="w-4 h-4" />
                                </IconButton>
                                <IconButton v-if="r.status !== 'rejected'" label="Reject review" tone="danger" @click="setStatus(r, 'rejected')">
                                    <X class="w-4 h-4" />
                                </IconButton>
                                <IconButton label="Reply" @click="startReply(r)">
                                    <MessageSquareReply class="w-4 h-4" />
                                </IconButton>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div v-if="pagination && pagination.last_page > 1" class="flex items-center justify-between mt-4 text-sm">
            <p class="text-zinc-500">Page {{ pagination.page }} of {{ pagination.last_page }} · {{ pagination.total }} reviews</p>
            <div class="flex gap-2">
                <button :disabled="pagination.page <= 1" @click="page--; fetchAll()" class="border border-zinc-300 px-3 py-1 disabled:opacity-40">Prev</button>
                <button :disabled="pagination.page >= pagination.last_page" @click="page++; fetchAll()" class="border border-zinc-300 px-3 py-1 disabled:opacity-40">Next</button>
            </div>
        </div>
    </div>
</template>

// apps/admin/src/app/reviews/page.tsx
"use client";

import { useEffect, useState, FormEvent } from "react";
import { Star, Check, X } from "lucide-react";
import { api } from "@/lib/api";
import { useAuthGate } from "@/lib/useAuthGate";
import type { Review } from "@/lib/types";
import { AdminShell } from "@/components/AdminShell";
import { useDialog } from "@/components/Dialog";
import { Pagination } from "@/components/Pagination";
import {
  Modal,
  Field,
  PageHeader,
  inputCls,
  btnPrimary,
  btnGhost,
  btnDanger,
} from "@/components/Modal";

const FILTERS = ["pending", "approved", "rejected", "all"] as const;
type Filter = (typeof FILTERS)[number];

export default function ReviewsPage() {
  const { user, loading } = useAuthGate();
  const dialog = useDialog();
  const [reviews, setReviews] = useState<Review[]>([]);
  const [count, setCount] = useState(0);
  const [filter, setFilter] = useState<Filter>("pending");
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Review | null>(null);
  const [busy, setBusy] = useState(false);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const load = async () => {
    const params = new URLSearchParams({
      limit: String(pageSize),
      offset: String((page - 1) * pageSize),
    });
    if (filter !== "all") params.set("status", filter);
    const res = await api.get<{ reviews: Review[]; count: number }>(
      `/admin/reviews?${params.toString()}`
    );
    setReviews(res.reviews);
    setCount(res.count);
  };

  useEffect(() => {
    if (user) void load();
  }, [user, filter, page, pageSize]);

  useEffect(() => { setPage(1); }, [filter]);

  const onUpdateStatus = async (r: Review, status: Review["status"]) => {
    await api.patch(`/admin/reviews/${r.id}`, { status });
    await load();
  };

  const onDelete = async (r: Review) => {
    const ok = await dialog.confirm({
      title: "Delete this review?",
      message: (
        <>
          “{r.title}” by{" "}
          <span className="font-medium">{r.customer_name || r.customer_email || "anonymous"}</span>
        </>
      ),
      tone: "danger",
      confirmLabel: "Delete review",
    });
    if (!ok) return;
    await api.delete(`/admin/reviews/${r.id}`);
    await load();
  };

  const onSubmit = async (e: FormEvent<HTMLFormElement>) => {
    if (!editing) return;
    e.preventDefault();
    setBusy(true);
    const fd = new FormData(e.currentTarget);
    try {
      await api.patch(`/admin/reviews/${editing.id}`, {
        admin_response: String(fd.get("admin_response") || "") || null,
      });
      setOpen(false);
      await load();
    } finally {
      setBusy(false);
    }
  };

  if (loading || !user) {
    return (
      <div className="flex h-screen items-center justify-center">
        <p className="font-script text-2xl text-[var(--gold-dark)]">Bless</p>
      </div>
    );
  }

  return (
    <AdminShell user={user}>
      <PageHeader
        title="Reviews"
        subtitle="Approve, reject, or respond to product reviews."
      />

      <div className="mb-6 flex gap-2">
        {FILTERS.map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className="rounded-full px-4 py-1.5 text-[10px] font-semibold uppercase tracking-luxe transition-colors"
            style={
              filter === f
                ? { background: "var(--ink)", color: "white" }
                : { background: "white", color: "var(--ink-muted)", border: "1px solid var(--line)" }
            }
          >
            {f}
          </button>
        ))}
      </div>

      <div className="space-y-4">
        {reviews.map((r) => (
          <article
            key={r.id}
            className="bg-white p-6 transition-shadow hover:shadow-sm"
            style={{ border: "1px solid var(--line)", borderRadius: 4 }}
          >
            <div className="flex items-start justify-between gap-6">
              <div className="flex-1 min-w-0">
                <div className="mb-2 flex items-center gap-3 flex-wrap">
                  <Stars value={r.rating} />
                  <span className="font-display text-lg font-medium tracking-soft">{r.title}</span>
                  <StatusBadge status={r.status} />
                  {r.is_verified_purchase && (
                    <span className="badge badge-success">Verified</span>
                  )}
                </div>
                <p className="text-sm leading-relaxed text-[var(--ink-light)]">{r.content}</p>
                <p className="mt-3 text-[10px] uppercase tracking-luxe text-[var(--ink-muted)]">
                  by {r.customer_name || r.customer_email || "anonymous"} · on{" "}
                  <span className="text-[var(--gold-dark)]">{r.product_title || r.product_id}</span>
                </p>
                {r.admin_response && (
                  <div
                    className="mt-4 px-4 py-3 text-sm"
                    style={{
                      borderLeft: "2px solid var(--gold)",
                      background: "var(--cream)",
                    }}
                  >
                    <p className="text-[10px] font-semibold uppercase tracking-luxe text-[var(--gold-dark)]">
                      Admin response
                    </p>
                    <p className="mt-1 text-[var(--ink-light)]">{r.admin_response}</p>
                  </div>
                )}
              </div>
              <div className="flex flex-col items-end gap-1.5 shrink-0">
                {r.status !== "approved" && (
                  <button onClick={() => onUpdateStatus(r, "approved")} className={btnPrimary}>
                    <Check className="mr-1.5 h-3.5 w-3.5" /> Approve
                  </button>
                )}
                {r.status !== "rejected" && (
                  <button onClick={() => onUpdateStatus(r, "rejected")} className={btnGhost}>
                    <X className="mr-1.5 h-3.5 w-3.5" /> Reject
                  </button>
                )}
                <button onClick={() => { setEditing(r); setOpen(true); }} className={`${btnGhost} btn-sm`}>
                  {r.admin_response ? "Edit reply" : "Add reply"}
                </button>
                <button onClick={() => onDelete(r)} className={btnDanger}>Delete</button>
              </div>
            </div>
          </article>
        ))}
        {reviews.length === 0 && (
          <div
            className="bg-white p-16 text-center"
            style={{ border: "1px solid var(--line)", borderRadius: 4 }}
          >
            <p className="font-display text-2xl text-[var(--ink-muted)]">No reviews to show</p>
          </div>
        )}
        {count > 0 && (
          <div
            className="bg-white"
            style={{ border: "1px solid var(--line)", borderRadius: 4 }}
          >
            <Pagination
              page={page}
              pageSize={pageSize}
              total={count}
              onPageChange={setPage}
              onPageSizeChange={(s) => { setPageSize(s); setPage(1); }}
              itemNoun="reviews"
            />
          </div>
        )}
      </div>

      <Modal
        open={open}
        onClose={() => setOpen(false)}
        title="Admin response"
        footer={
          <>
            <button onClick={() => setOpen(false)} className={btnGhost} type="button">Cancel</button>
            <button form="review-resp" type="submit" disabled={busy} className={btnPrimary}>
              {busy ? "Saving…" : "Save"}
            </button>
          </>
        }
      >
        {editing && (
          <form id="review-resp" onSubmit={onSubmit} className="space-y-4">
            <Field label={`Replying to: ${editing.title}`}>
              <textarea
                name="admin_response"
                rows={5}
                defaultValue={editing.admin_response || ""}
                className="textarea"
              />
            </Field>
          </form>
        )}
      </Modal>
    </AdminShell>
  );
}

function Stars({ value }: { value: number }) {
  return (
    <span className="flex items-center gap-0.5">
      {[1, 2, 3, 4, 5].map((n) => (
        <Star
          key={n}
          className="h-3.5 w-3.5"
          fill={n <= value ? "var(--gold)" : "transparent"}
          color="var(--gold)"
        />
      ))}
    </span>
  );
}

function StatusBadge({ status }: { status: Review["status"] }) {
  const cls =
    status === "approved" ? "badge badge-success" :
    status === "rejected" ? "badge badge-danger" : "badge badge-warn";
  return <span className={cls}>{status}</span>;
}
