// apps/storefront/src/components/layout/Header.tsx
"use client";

import { useState, useRef, useEffect, useMemo } from "react";
import Link from "next/link";
import Image from "next/image";
import { usePathname, useSearchParams } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { Search, User, Heart, ShoppingBag, Menu, ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";
import { useUIStore } from "@/stores/ui";
import { useCartStore } from "@/stores/cart";
import { useWishlistStore } from "@/stores/wishlist";
import { AnnouncementBar } from "./AnnouncementBar";

// Main navigation with submenus
const navLinks = [
  {
    label: "Women",
    href: "/shop?category=women",
    submenu: {
      featured: {
        title: "Featured",
        items: [
          { href: "/shop", label: "New Arrivals", icon: "✨" },
          { href: "/shop?category=women", label: "Bestsellers", icon: "🏆" },
          { href: "/shop?category=women", label: "Trending Now", icon: "🔥" },
        ],
      },
      categories: {
        title: "Categories",
        items: [
          { href: "/shop?category=dresses", label: "Dresses" },
          { href: "/shop?category=tops", label: "Tops & Blouses" },
          { href: "/shop?category=bottoms", label: "Pants & Skirts" },
          { href: "/shop?category=women", label: "Matching Sets" },
          { href: "/shop?category=outerwear", label: "Jackets & Coats" },
          { href: "/shop?category=women", label: "Knitwear" },
        ],
      },
      occasions: {
        title: "Shop by Occasion",
        items: [
          { href: "/shop?category=women", label: "Date Night" },
          { href: "/shop?category=women", label: "Work Luxe" },
          { href: "/shop?category=women", label: "Casual Chic" },
          { href: "/shop?category=women", label: "Evening & Formal" },
          { href: "/shop?category=women", label: "Vacation Ready" },
        ],
      },
      accessories: {
        title: "Accessories",
        items: [
          { href: "/shop?category=accessories", label: "Bags" },
          { href: "/shop?category=accessories", label: "Jewelry" },
          { href: "/shop?category=accessories", label: "Shoes" },
          { href: "/shop?category=accessories", label: "Scarves" },
        ],
      },
    },
  },
  {
    label: "Men",
    href: "/shop?category=men",
    submenu: {
      featured: {
        title: "Featured",
        items: [
          { href: "/shop?category=men", label: "New Arrivals", icon: "✨" },
          { href: "/shop?category=men", label: "Bestsellers", icon: "🏆" },
        ],
      },
      categories: {
        title: "Categories",
        items: [
          { href: "/shop?category=men", label: "Suits & Blazers" },
          { href: "/shop?category=men", label: "Shirts" },
          { href: "/shop?category=men", label: "Trousers" },
          { href: "/shop?category=men", label: "Knitwear" },
          { href: "/shop?category=outerwear", label: "Jackets & Coats" },
          { href: "/shop?category=men", label: "Casual Wear" },
        ],
      },
      occasions: {
        title: "Shop by Occasion",
        items: [
          { href: "/shop?category=men", label: "Business" },
          { href: "/shop?category=men", label: "Smart Casual" },
          { href: "/shop?category=men", label: "Weekend" },
        ],
      },
      accessories: {
        title: "Accessories",
        items: [
          { href: "/shop?category=accessories", label: "Watches" },
          { href: "/shop?category=accessories", label: "Belts" },
          { href: "/shop?category=accessories", label: "Shoes" },
          { href: "/shop?category=accessories", label: "Bags" },
        ],
      },
    },
  },
  {
    label: "Children",
    href: "/shop?category=children",
    submenu: {
      featured: {
        title: "Featured",
        items: [
          { href: "/shop?category=children", label: "New Arrivals", icon: "✨" },
          { href: "/shop?category=children", label: "Bestsellers", icon: "🏆" },
        ],
      },
      categories: {
        title: "Girls",
        items: [
          { href: "/shop?category=children", label: "Dresses" },
          { href: "/shop?category=children", label: "Tops" },
          { href: "/shop?category=children", label: "Bottoms" },
          { href: "/shop?category=children", label: "Sets" },
        ],
      },
      occasions: {
        title: "Boys",
        items: [
          { href: "/shop?category=children", label: "Shirts" },
          { href: "/shop?category=children", label: "Trousers" },
          { href: "/shop?category=children", label: "Casual" },
          { href: "/shop?category=children", label: "Formal" },
        ],
      },
      accessories: {
        title: "Baby",
        items: [
          { href: "/shop?category=children", label: "Clothing" },
          { href: "/shop?category=children", label: "Accessories" },
          { href: "/shop?category=children", label: "Gift Sets" },
        ],
      },
    },
  },
  { label: "Sale", href: "/shop", isSale: true },
];

export function Header() {
  const [activeMenu, setActiveMenu] = useState<string | null>(null);
  const [mounted, setMounted] = useState(false);
  const menuTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const pathname = usePathname();
  const searchParams = useSearchParams();
  
  const { isHeaderScrolled, setHeaderScrolled, openMobileNav, openSearch } = useUIStore();
  const cartItemCount = useCartStore((state) => state.getItemCount());
  const wishlistCount = useWishlistStore((state) => state.getItemCount());
  const toggleCart = useCartStore((state) => state.toggleCart);

  // Determine which nav item is currently active based on URL
  const activeNavItem = useMemo(() => {
    if (pathname !== "/shop") return null;
    const category = searchParams.get("category");
    if (!category) return null;
    
    // Map category to nav labels
    if (["women", "dresses", "tops", "bottoms", "outerwear"].includes(category)) {
      return "Women";
    }
    if (category === "men") return "Men";
    if (category === "children") return "Children";
    if (category === "accessories") return "Women"; // accessories under women for now
    return null;
  }, [pathname, searchParams]);

  // Prevent hydration mismatch
  useEffect(() => {
    setMounted(true);
  }, []);

  // Handle scroll effect
  useEffect(() => {
    const handleScroll = () => {
      setHeaderScrolled(window.scrollY > 50);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, [setHeaderScrolled]);

  // Menu hover handlers with delay to prevent flickering
  const handleMenuEnter = (label: string) => {
    if (menuTimeoutRef.current) {
      clearTimeout(menuTimeoutRef.current);
    }
    setActiveMenu(label);
  };

  const handleMenuLeave = () => {
    menuTimeoutRef.current = setTimeout(() => {
      setActiveMenu(null);
    }, 150);
  };

  const handleSubmenuEnter = () => {
    if (menuTimeoutRef.current) {
      clearTimeout(menuTimeoutRef.current);
    }
  };

  return (
    <>
      <AnnouncementBar />
      <header
        className={cn(
          "sticky top-0 z-50 transition-all duration-300",
          "border-b border-gold/20",
          isHeaderScrolled
            ? "bg-cream/95 backdrop-blur-md shadow-lg shadow-gold/10"
            : "bg-cream"
        )}
      >
        <div className="max-w-[1600px] mx-auto px-[5%]">
          <div className="flex items-center justify-between py-4">
            {/* Mobile Menu Button */}
            <button
              onClick={openMobileNav}
              className="lg:hidden p-2 -ml-2 hover:text-gold transition-colors"
              aria-label="Open menu"
            >
              <Menu className="w-6 h-6" />
            </button>

            {/* Logo - overflows header for larger appearance */}
            <Link href="/" className="flex items-center flex-shrink-0">
              <Image
                src="/logo.png"
                alt="BLESSLUXE"
                width={200}
                height={200}
                className={cn(
                  "w-auto transition-all duration-300 -my-4",
                  isHeaderScrolled ? "h-16" : "h-20"
                )}
                priority
              />
            </Link>

            {/* Desktop Navigation with Mega Menu */}
            <nav className="hidden lg:flex items-center gap-8">
              {navLinks.map((link) => (
                <div
                  key={link.label}
                  className="relative"
                  onMouseEnter={() => link.submenu && handleMenuEnter(link.label)}
                  onMouseLeave={handleMenuLeave}
                >
                  <Link
                    href={link.href}
                    className={cn(
                      "relative flex items-center gap-1.5 font-body text-sm font-medium tracking-widest uppercase",
                      "py-3 transition-colors",
                      link.isSale ? "text-red-600" : "text-black hover:text-gold",
                      // Active state when hovering mega menu
                      activeMenu === link.label && "text-gold",
                      // Active state when on corresponding page
                      activeNavItem === link.label && "text-gold",
                      // Underline animation
                      "after:absolute after:bottom-0 after:left-0",
                      "after:w-0 after:h-0.5 after:bg-gold",
                      "after:transition-all after:duration-300",
                      "hover:after:w-full",
                      // Show underline when active (hover or current page)
                      (activeMenu === link.label || activeNavItem === link.label) && "after:w-full"
                    )}
                  >
                    {link.label}
                    {link.submenu && (
                      <ChevronDown
                        className={cn(
                          "w-3.5 h-3.5 transition-transform duration-200",
                          activeMenu === link.label && "rotate-180"
                        )}
                      />
                    )}
                  </Link>
                </div>
              ))}
            </nav>

            {/* Header Actions */}
            <div className="flex items-center gap-5">
              <button
                onClick={openSearch}
                className="p-2 hover:text-gold transition-colors hover:scale-110"
                aria-label="Search"
              >
                <Search className="w-5 h-5" strokeWidth={1.5} />
              </button>

              <Link
                href="/account"
                className="hidden sm:block p-2 hover:text-gold transition-colors hover:scale-110"
                aria-label="Account"
              >
                <User className="w-5 h-5" strokeWidth={1.5} />
              </Link>

              <Link
                href="/wishlist"
                className="relative p-2 hover:text-gold transition-colors hover:scale-110"
                aria-label="Wishlist"
              >
                <Heart className="w-5 h-5" strokeWidth={1.5} />
                {mounted && wishlistCount > 0 && (
                  <span className="absolute -top-1 -right-1 w-4 h-4 bg-gold text-white text-[10px] font-semibold rounded-full flex items-center justify-center animate-pop-in">
                    {wishlistCount}
                  </span>
                )}
              </Link>

              <button
                onClick={toggleCart}
                className="relative p-2 hover:text-gold transition-colors hover:scale-110"
                aria-label="Cart"
              >
                <ShoppingBag className="w-5 h-5" strokeWidth={1.5} />
                {mounted && cartItemCount > 0 && (
                  <span className="absolute -top-1 -right-1 w-4 h-4 bg-gold text-white text-[10px] font-semibold rounded-full flex items-center justify-center animate-pop-in">
                    {cartItemCount}
                  </span>
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Mega Menu Dropdown */}
        <AnimatePresence>
          {activeMenu && navLinks.find(l => l.label === activeMenu)?.submenu && (
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
              onMouseEnter={handleSubmenuEnter}
              onMouseLeave={handleMenuLeave}
              className="absolute left-0 right-0 bg-white shadow-xl border-t border-gold/10 z-40"
            >
              <div className="max-w-[1400px] mx-auto px-[5%] py-10">
                <div className="grid grid-cols-4 gap-12">
                  {(() => {
                    const submenu = navLinks.find(l => l.label === activeMenu)?.submenu;
                    if (!submenu) return null;
                    return Object.entries(submenu).map(([key, section]) => (
                      <div key={key}>
                        <h3 className="font-display text-sm tracking-widest uppercase text-gold mb-5 pb-2 border-b border-gold/20">
                          {section.title}
                        </h3>
                        <ul className="space-y-3">
                          {section.items.map((item) => (
                            <li key={item.href}>
                              <Link
                                href={item.href}
                                className="flex items-center gap-2 text-sm text-black/70 hover:text-gold transition-colors group"
                              >
                                {"icon" in item && (
                                  <span>{item.icon}</span>
                                )}
                                <span className="group-hover:translate-x-1 transition-transform">
                                  {item.label}
                                </span>
                              </Link>
                            </li>
                          ))}
                        </ul>
                      </div>
                    ));
                  })()}
                </div>

                {/* Featured promo in mega menu */}
                <div className="mt-10 pt-8 border-t border-gold/10">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="font-script text-2xl text-gold">New Season</p>
                      <p className="text-black/70 text-sm mt-1">Up to 40% off selected styles</p>
                    </div>
                    <Link
                      href="/collections/sale"
                      className="inline-block bg-gold text-white px-8 py-3 text-xs font-semibold tracking-widest uppercase hover:bg-gold-dark transition-colors"
                    >
                      Shop Now
                    </Link>
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </header>
    </>
  );
}

// Lavavel_Version/resources/js/storefront/components/Header.vue
<script>
export default {
    name: 'StoreHeader',
    data() {
        return {
            scrolled: false,
            activeMenu: null,
            navLinks: [
                {
                    label: 'Women',
                    href: '/shop?category=women',
                    submenu: [
                        { label: 'Dresses', href: '/shop?category=women&type=dresses' },
                        { label: 'Tops & Blouses', href: '/shop?category=women&type=tops' },
                        { label: 'Trousers & Skirts', href: '/shop?category=women&type=trousers' },
                        { label: 'Bags', href: '/shop?category=women&type=bags' },
                    ],
                },
                {
                    label: 'Men',
                    href: '/shop?category=men',
                    submenu: [
                        { label: 'Shirts', href: '/shop?category=men&type=shirts' },
                        { label: 'Trousers', href: '/shop?category=men&type=trousers' },
                        { label: 'Suits', href: '/shop?category=men&type=suits' },
                    ],
                },
                {
                    label: 'Children',
                    href: '/shop?category=children',
                    submenu: [
                        { label: 'Girls', href: '/shop?category=children&type=girls' },
                        { label: 'Boys', href: '/shop?category=children&type=boys' },
                    ],
                },
                { label: 'Sale', href: '/shop?sale=true', isSale: true },
            ],
        };
    },
    mounted() {
        window.addEventListener('scroll', this.handleScroll, { passive: true });
        this.handleScroll();
    },
    beforeUnmount() {
        window.removeEventListener('scroll', this.handleScroll);
    },
    methods: {
        handleScroll() {
            this.scrolled = window.scrollY > 24;
        },
    },
};
</script>

<template>
    <header
        :class="[
            'sticky top-0 z-40 transition-all duration-300 border-b border-gold/10',
            scrolled ? 'bg-cream/95 backdrop-blur shadow-sm' : 'bg-cream/80',
        ]"
    >
        <div class="max-w-[1600px] mx-auto px-[5%]">
            <div class="flex items-center justify-between py-4">
                <!-- Mobile menu button -->
                <button
                    class="lg:hidden p-2 -ml-2 hover:text-gold transition-colors"
                    aria-label="Open menu"
                >
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5M3.75 17.25h16.5" />
                    </svg>
                </button>

                <!-- Logo -->
                <router-link to="/" class="flex items-center flex-shrink-0">
                    <img
                        src="/logo.png"
                        alt="BLESSLUXE"
                        :class="[
                            'w-auto transition-all duration-300 -my-4',
                            scrolled ? 'h-14 sm:h-16' : 'h-16 sm:h-20',
                        ]"
                    />
                </router-link>

                <!-- Desktop nav -->
                <nav class="hidden lg:flex items-center gap-8">
                    <router-link
                        to="/shop/packs"
                        active-class="text-gold"
                        class="font-body text-sm font-medium tracking-widest uppercase py-3 text-black hover:text-gold transition-colors"
                    >
                        Packs
                    </router-link>
                    <div
                        v-for="link in navLinks"
                        :key="link.label"
                        class="relative"
                        @mouseenter="activeMenu = link.submenu ? link.label : null"
                        @mouseleave="activeMenu = null"
                    >
                        <a
                            :href="link.href"
                            :class="[
                                'relative flex items-center gap-1.5 font-body text-sm font-medium tracking-widest uppercase py-3 transition-colors',
                                link.isSale ? 'text-red-600' : 'text-black hover:text-gold',
                                activeMenu === link.label && 'text-gold',
                            ]"
                        >
                            {{ link.label }}
                            <svg
                                v-if="link.submenu"
                                :class="['w-3.5 h-3.5 transition-transform', activeMenu === link.label ? 'rotate-180' : '']"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="2"
                                viewBox="0 0 24 24"
                            >
                                <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
                            </svg>
                        </a>
                        <div
                            v-if="link.submenu && activeMenu === link.label"
                            class="absolute left-0 top-full pt-3 z-30"
                        >
                            <div class="bg-white shadow-xl border border-gold/10 min-w-[220px] py-3">
                                <a
                                    v-for="sub in link.submenu"
                                    :key="sub.label"
                                    :href="sub.href"
                                    class="block px-5 py-2 text-sm text-black/80 hover:text-gold hover:bg-cream-dark transition-colors"
                                >
                                    {{ sub.label }}
                                </a>
                            </div>
                        </div>
                    </div>
                </nav>

                <!-- Right icons -->
                <div class="flex items-center gap-1.5">
                    <button class="p-2 hover:text-gold transition-colors" aria-label="Search">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
                        </svg>
                    </button>
                    <router-link to="/account" class="p-2 hover:text-gold transition-colors" aria-label="Account">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                        </svg>
                    </router-link>
                    <router-link to="/wishlist" class="p-2 hover:text-gold transition-colors" aria-label="Wishlist">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
                        </svg>
                    </router-link>
                    <router-link to="/cart" class="p-2 hover:text-gold transition-colors relative" aria-label="Cart">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
                        </svg>
                    </router-link>
                </div>
            </div>
        </div>
    </header>
</template>
